# docker-compose.txt
version: "3"
services:
  cust-tracker:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://root:secret@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - .:/cust-tracker/
      - /cust-tracker/node_modules

  postgres:
    image: postgres:12-alpine
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: customer_tracker